name: GitHub Activity Generator

on:
  schedule:
    - cron: "0 * * * *"   # Runs every hour
  workflow_dispatch:      # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}

      - name: Run generator
        run: |
          python3 contribute.py --max_commits=12 --frequency=70 --repository=git@github.com:jay8patel/boost.git

      - name: Push changes
        run: |
          git config user.name "Jay Patel"
          git config user.email "jaykp7246@gmail.com"
          git add .
          git commit -m "Automated contribution"
          git push origin main
