name: Daily Contribution

on:
  schedule:
    - cron: '0 12 * * *' # Runs daily at noon UTC
  workflow_dispatch:
    inputs:
      days_back:
        description: 'How many days back to go?'
        required: true
        default: '0'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Configure Git Identity
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Run Contribution Script
        run: |
          DAYS=${{ inputs.days_back || '0' }}
          
          # SETTINGS FOR NATURAL LOOK:
          # --frequency 85    -> 85% chance to commit (15% chance to skip the day)
          # --max_commits 15  -> Randomly makes 1 to 15 commits per day (Varied green colors)
          python daily_bot.py --days_before $DAYS --days_after 1 --frequency 85 --max_commits 15

      - name: Push changes
        run: |
          git pull origin main --rebase || echo "No changes to pull"
          git push origin HEAD:main
